// Content-only: no logic here. See ../greeting.js for how these lines are rendered.
export default {
  contactEmail: "projectjinam@gmail.com",

  devanagari: [
    "*जय जिनेन्द्र!*",
    "",
    "`JINAM Chatbot` में आपका स्वागत है। यह प्लेटफॉर्म जैन दर्शन, मूल्यों और इतिहास को समझने के इच्छुक जिज्ञासुओं के लिए समर्पित है।",
    "",
    "_हमारा लक्ष्य प्राचीन शास्त्रों में संरक्षित आचार्यों और मुनिराजों के शाश्वत ज्ञान को तथा आधुनिक जैन विद्वानों के समर्पित प्रयासों को, सरल और सुगम भाषा में आप तक पहुँचाना है।_",
    "",
    "आप जैन धर्म से संबंधित अपने प्रश्न को हिंदी या अंग्रेजी में पूछ सकते हैं।",
    "",
    "जैन धर्म और आत्म-बोध की इस सार्थक खोजपूर्ण यात्रा के लिए हमारी मंगल भावनाएँ।",
    "",
    "सधन्यवाद,",
    "टीम JINAM",
    "(```TATTVAM``` और ```Origen Systems``` की एक पहल)",
    "सुझाव: {{CONTACT}}",
    "",
    "`कृपया ध्यान दें:`",
    "```JINAM Chatbot``` केवल एक सहायक है, जो उत्तरों के साथ जैन ग्रंथों के संदर्भ प्रदान करता है। इसमें त्रुटियाँ हो सकती हैं—कृपया प्रत्येक उत्तर के साथ दिए गए मूल ग्रंथों पर ही विश्वास करें।",
  ],

  latin: [
    "*Jai Jinendra!*",
    "",
    "Welcome to `JINAM Chatbot`. This platform is dedicated to helping seekers explore Jain philosophy, values, and history.",
    "",
    "_Our mission is to guide you through the timeless wisdom of our Acharyas and Munirajas as preserved in ancient scriptures, supported by the dedicated efforts of modern Jain scholars in simple, accessible language._",
    "",
    "You may ask your questions related to Jainism in either English or Hindi.",
    "",
    "We wish you a meaningful journey of discovering Jainism and the self.",
    "",
    "Thanks,",
    "Team JINAM",
    "(An initiative by ```TATTVAM``` and ```Origen Systems```)",
    "Feedback: {{CONTACT}}",
    "",
    "`PLEASE NOTE:`",
    "```JINAM Chatbot``` is only an *assistant* in providing answers along-with the references to Jain Texts. It may make mistakes. Only trust the original literature cited with each answer.",
  ],
};
