// Content-only: no logic here. See ../greeting.js for how these lines are rendered.
export default {
  contactEmail: "contact@swalakshya.me",

  devanagari: [
    "*जय जिनेन्द्र!*",
    "",
    "`Swalakshya AI` एक AI-आधारित खोज मंच है, जो पूज्य गुरुदेव श्री कानजी स्वामी द्वारा दिए गए हज़ारों प्रवचनों, सैकड़ों मूल दिगंबर जैन शास्त्रों, तथा समकालीन जैन विद्वानों द्वारा रचित जैन साहित्य पर आधारित है।",
    "",
    "_हमारा उद्देश्य मुमुक्षुओं को इस विशाल आध्यात्मिक साहित्य के माध्यम से जैन तत्त्व को सीधे समझने में सहायता करना है।_",
    "",
    "आप जैन धर्म से संबंधित अपने प्रश्न हिंदी, गुजराती या अंग्रेजी में पूछ सकते हैं।",
    "",
    "Swalakshya AI केवल इसी मूल एवं प्रामाणिक जैन साहित्य से ही उत्तर देगा तथा प्रत्येक उत्तर के साथ संदर्भ भी देगा, जिससे आप मूल स्रोत से उत्तर की जाँच स्वयं कर सकें।",
    "",
    "स्वाध्याय और आत्म-बोध की इस सार्थक यात्रा के लिए हमारी मंगल भावनाएँ।",
    "",
    "सधन्यवाद,",
    "टीम Swalakshya",
    "",
    "अपना [feedback_button:सुझाव भेजें], या हमें {{CONTACT}} पर ईमेल करें।",
    "",
    "`कृपया ध्यान दें:`",
    "```Swalakshya AI``` केवल एक सहायक है, जो इस जैन साहित्य में से संदर्भ प्रदान करता है। इसमें त्रुटियाँ हो सकती हैं—कृपया प्रत्येक उत्तर के साथ दिए गए मूल संदर्भ पर ही विश्वास करें।",
  ],

  latin: [
    "*Jai Jinendra!*",
    "",
    "This is `Swalakshya AI`, an AI-powered search platform built on thousands of spiritual discourses (Pravachans) delivered by Pujya Gurudev Shri Kanji Swami, hundreds of original Digambar Jain Scriptures, and Jain Literature authored by contemporary Jain Scholars.",
    "",
    "_Our mission is to help spiritual seekers (Mumukshus) explore Jain Tattva directly through this wealth of spiritual literature._",
    "",
    "You may ask your questions related to Jainism in Hindi, Gujarati, or English.",
    "",
    "Swalakshya AI will only return answers from this original and authentic Jain literature and will also cite references so that you can cross-verify the answer directly from the source.",
    "",
    "We wish you a meaningful journey of Swadhyay and self-discovery.",
    "",
    "Thanks,",
    "Team Swalakshya",
    "",
    "Send us your [feedback_button:feedback], or email us at {{CONTACT}}.",
    "",
    "`PLEASE NOTE:`",
    "```Swalakshya AI``` is only an *assistant* that surfaces references from this Jain literature. It may make mistakes. Only trust the original references cited along with every answer.",
  ],
};
