FROM node:20-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --omit=dev

COPY src ./src
COPY prompts_sets ./prompts_sets
COPY test ./test

ENV NODE_ENV=test

CMD ["npm", "test"]
